"""Golden-curve input definition (22 TYSO-style pillars, TRY-style inversion).

Kept as a Python module so the test and the helper script share one source of truth.
The output (bootstrapped DFs) lives next to this file as ``golden_curve.json`` and is
regenerated by ``scripts/regen_golden_curve.py`` when conventions or fixture rates
change intentionally.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from rates.core.bootstrap import _add_months, _roll
from rates.core.calendar import HolidayCalendar
from rates.core.types import BusinessDayConvention, MarketData, MarketQuote

GOLDEN_VAL_DATE = date(2026, 6, 12)

# (label, end_date_callable, rate). Rates resemble a deeply inverted TRY OIS curve
# (45% at the short end fading to 33.25% at 10Y) — representative of recent regimes
# but synthetic.
_TENOR_SPECS: tuple[tuple[str, str, float], ...] = (
    ("TYSO1D", "1D", 0.4780),
    ("TYSO1W", "1W", 0.4775),
    ("TYSO2W", "2W", 0.4770),
    ("TYSO1M", "1M", 0.4750),
    ("TYSO2M", "2M", 0.4700),
    ("TYSO3M", "3M", 0.4650),
    ("TYSO4M", "4M", 0.4580),
    ("TYSO5M", "5M", 0.4520),
    ("TYSO6M", "6M", 0.4450),
    ("TYSO9M", "9M", 0.4300),
    ("TYSO1Y", "1Y", 0.4200),
    ("TYSO18M", "18M", 0.4000),
    ("TYSO2Y", "2Y", 0.3850),
    ("TYSO3Y", "3Y", 0.3650),
    ("TYSO4Y", "4Y", 0.3550),
    ("TYSO5Y", "5Y", 0.3450),
    ("TYSO6Y", "6Y", 0.3400),
    ("TYSO7Y", "7Y", 0.3370),
    ("TYSO8Y", "8Y", 0.3345),
    ("TYSO9Y", "9Y", 0.3330),
    ("TYSO10Y", "10Y", 0.3325),
    ("TYSO15Y", "15Y", 0.3300),  # Extra >10Y to exercise brentq beyond direct yearly.
)


def _parse_tenor_to_end_date(spec: str, val: date, cal: HolidayCalendar) -> date:
    """Translate ``"3M"`` / ``"18M"`` / ``"1Y"`` / ``"10Y"`` into a rolled end-date.

    Days/weeks add calendar units then roll mod-following; months/years go through
    ``_add_months`` first.
    """
    unit = spec[-1]
    mag = int(spec[:-1])
    if unit == "D":
        from datetime import timedelta

        return _roll(val + timedelta(days=mag), cal, BusinessDayConvention.MODIFIED_FOLLOWING)
    if unit == "W":
        from datetime import timedelta

        return _roll(
            val + timedelta(days=7 * mag),
            cal,
            BusinessDayConvention.MODIFIED_FOLLOWING,
        )
    if unit == "M":
        return _roll(_add_months(val, mag), cal, BusinessDayConvention.MODIFIED_FOLLOWING)
    if unit == "Y":
        return _roll(_add_months(val, 12 * mag), cal, BusinessDayConvention.MODIFIED_FOLLOWING)
    raise ValueError(f"unknown tenor unit in {spec!r}")


def build_golden_market(cal: HolidayCalendar) -> MarketData:
    quotes: list[MarketQuote] = []
    for tenor_code, spec, rate in _TENOR_SPECS:
        end = _parse_tenor_to_end_date(spec, GOLDEN_VAL_DATE, cal)
        quotes.append(
            MarketQuote(
                tenor_code=tenor_code,
                tenor_days=(end - GOLDEN_VAL_DATE).days,
                start_date=GOLDEN_VAL_DATE,
                end_date=end,
                bid=None,
                ask=None,
                mid=rate,
                source="golden",
            )
        )
    return MarketData(quotes=tuple(quotes), valuation_date=GOLDEN_VAL_DATE, source="golden")


GOLDEN_PATH = Path(__file__).with_name("golden_curve.json")
